baseURL = "https://fred4impact.github.io/"
languageCode = "en-gb"
title = "Samuel O"
theme = "PaperMod"
paginate = 8

[params]
  author = "Samuel O"
  bio = "DevOps, and automation enthusiast with a passion for continuous learning. I share practical insights, best practices, and real-world lessons from my journey in cloud infrastructure, CI/CD, DevOps workflows, and automation."

  github = "https://github.com/fred4impact"

[taxonomies]
  tag = "tags"

[params.assets]
customCSS = ["css/custom.css"]

[[menu.main]]
name = "Demos"
url = "/demos/"
weight = 1

[[menu.main]]
name = "DevOps Notes"
url = "/devops/"
weight = 2

[[menu.main]]
name = "Articles"
url = "/writings/"
weight = 3

[[menu.main]]
name = "Cheatsheets"
url = "/cheatsheets/"
weight = 4

[[menu.main]]
name = "GitHub"
url = "https://github.com/fred4impact"
weight = 5


[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true