baseURL = "https://fred4impact.github.io/"
languageCode = "en-gb"
title = "Samuel O"
theme = "PaperMod"
paginate = 8

[params]
  author = "Samuel O"
  bio = "DevOps, and automation enthusiast with a passion for continuous learning. I share practical insights, best practices, and real-world lessons from my journey in cloud infrastructure, CI/CD, DevOps workflows, and automation."

  github = "https://github.com/fred4impact"

[taxonomies]
  tag = "tags"

[params.assets]
customCSS = ["css/custom.css"]